### ISSUE TITLE
Improving the Event node

### ISSUE THREAD

**Issue by ahartman** [naimo84/node-red-contrib-ical-events#12] opened 2019-10-30 06:03 UTC
Dear Benjamin,

I am working intensively with the Event node and I can see some improvements making this and easier and more powerful object.
1. It should not be necessary to start the Event node with injecting a timestamp. It should start itself and should always restart after an event found. That is what a real event sensor does.
2. It is really necessary to send messages at the start of the event but also at the end; both are relevant state changes. I modeled my idea in Node-RED, please see below.
3. It would be very powerful indeed if the Event node could search in the summary based on a Regex expression for certain text. You could model trigger behaviours as I copied b below from the homebridge-daily-sensors module (that I use currently).
==============

- trigger : Notwithstanding the default behaviour the following settings are allowed for this property:
- match : The Trigger Event is triggered when at least one calendar event was found for the current time and the summary matches the specified regexp . The activation state is set to the value specified in the active-property.
- no-match : The Trigger Event is triggered when no valid calendar event was found. The activation state is set to the inverse value specified in the active-property.
- always : The Trigger Event is allways triggered. If a valid calendar event was found, the activation state is set to the value specified in the active-property. Otherwise it is set to the inverse.
===============
Please find below the modelling in Node-RED:
[flows.json.txt](https://github.com/naimo84/node-red-contrib-ical-events/files/3787172/flows.json.txt)

kind regards, andré hartman, belgium

**Comment by jseg** [comment] 2019-10-31 15:28
Hi André and Benjamin,

I'm using this node in a way that, I think, is similar to what you are doing, André. My application is to coordinate the daily startup and shutdown of computers and programs in a museum exhibit. We normally have a set weekly schedule, but sometimes there are special events that need to be scheduled. As you say, this sort of application is much easier with both onStart and onFinish event messages. I've attached the first draft of the flow I'm using to parse these events. I'm using switch nodes to parse and route event messages based the msg.summary property. The switch node also exposes rules to match using regex. I'm not using that feature because my event types won't be changing. Also, I'm not keeping track of explicit msg.on/msg.off properties, but this could be done simply with change nodes right before the switches. 

All that said, there is a major weakness with the node for this sort of state tracking application. Suppose you have light that has been turned on by a calendar event. If, while the event is in progress, you modify (or delete) the event in the calendar such that the end of the event is in that past, then no end message will be sent. The light will stay on. I'm of two minds about this behavior. 

On the one hand for state tracking applications it seems like a bug. Events that start should always end. One way to implement this would be to not delete the (finished) event start cronjobs while a corresponding event end uid remains in the possibleUid list. Then if an event start cronjob is in the startedEvents object and it doesn't have a matching event end uid in the list of possibleUids, then send an event end message. 

On the other hand, if the design goal is to focus the overall package on calendar parsing, I'd say the current behavior is the intended behavior. In this case, one work around might be to add a duration property to the event message to facilitate watchdog logic. While that data is already implicit in the msg.eventStart and msg.eventEnd properties, it would serve the idea that date calculations be handled by calendar objects. 

Warm regards,

John

Example Flow:
[{"id":"731fb1ca.44fbb","type":"tab","label":"Calendar Control","disabled":false,"info":""},{"id":"97a1dce7.b1079","type":"inject","z":"731fb1ca.44fbb","name":"Check Calendar","topic":"","payload":"","payloadType":"date","repeat":"600","crontab":"","once":true,"onceDelay":0.1,"x":150,"y":260,"wires":[["962e4459.30bde","38312709.c215e8"]]},{"id":"962e4459.30bde","type":"ical-events","z":"731fb1ca.44fbb","confignode":"f7b218db.76408","cron":"","name":"","offset":"0","x":360,"y":260,"wires":[["82ba4f20.76f108","d638c80c.7cade8"],["dd51858c.7f3bb","d638c80c.7cade8"]]},{"id":"82ba4f20.76f108","type":"switch","z":"731fb1ca.44fbb","name":"Start-up switch","property":"payload.summary","propertyType":"msg","rules":[{"t":"eq","v":"CraveBot","vt":"str"},{"t":"eq","v":"CalmingTable","vt":"str"},{"t":"eq","v":"CommunityWindow","vt":"str"}],"checkall":"true","repair":false,"outputs":3,"x":600,"y":180,"wires":[["70c8a53c.9a3c64"],["137a3832.2eef1"],["c46656e5.50e5b"]]},{"id":"dd51858c.7f3bb","type":"switch","z":"731fb1ca.44fbb","name":"Shutdown switch","property":"payload.summary","propertyType":"msg","rules":[{"t":"eq","v":"CraveBot","vt":"str"},{"t":"eq","v":"CalmingTable","vt":"str"},{"t":"eq","v":"CommunityWindow","vt":"str"}],"checkall":"true","repair":false,"outputs":3,"x":610,"y":340,"wires":[["83788fe9.465168"],["64a9bc51.21144c"],["b346f0c3.0db048"]]},{"id":"70c8a53c.9a3c64","type":"link out","z":"731fb1ca.44fbb","name":"To CraveBot Startup","links":["39a6d73e.211a58"],"x":775,"y":140,"wires":[]},{"id":"137a3832.2eef1","type":"link out","z":"731fb1ca.44fbb","name":"To Calming Table Startup","links":["d51d1d30.8803f8"],"x":775,"y":180,"wires":[]},{"id":"c46656e5.50e5b","type":"link out","z":"731fb1ca.44fbb","name":"To Community Window Startup","links":["800fc8c3.55863"],"x":775,"y":220,"wires":[]},{"id":"83788fe9.465168","type":"link out","z":"731fb1ca.44fbb","name":"To CraveBot Shutdown","links":["18496e7e.581e82"],"x":775,"y":300,"wires":[]},{"id":"64a9bc51.21144c","type":"link out","z":"731fb1ca.44fbb","name":"To CalmingTable Shutdown","links":["bfa1a22b.e6728"],"x":775,"y":340,"wires":[]},{"id":"b346f0c3.0db048","type":"link out","z":"731fb1ca.44fbb","name":"To Community Window Shutdown","links":["eae72721.79cdb"],"x":775,"y":380,"wires":[]},{"id":"d638c80c.7cade8","type":"debug","z":"731fb1ca.44fbb","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":610,"y":260,"wires":[]},{"id":"38312709.c215e8","type":"debug","z":"731fb1ca.44fbb","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":350,"y":300,"wires":[]},{"id":"f7b218db.76408","type":"ical-config","z":"","url":"https://calendar.google.com/calendar/ical/qp84182c2tprp1f2qdn4b66adg%40group.calendar.google.com/private-6c8e166d9b551e9421b1d1dc15eab23c/basic.ics","username":"","password":"","caldav":"false","name":"test","language":"en","replacedates":false}]

**Comment by ahartman** [comment] 2019-11-01 05:53
Benjamin, John,

John, welcome to this exchange of views.

I do not think the user should have to define any cron jobs at all, that should be internal to the node itself. In my view the node regularly polls the calendar, polling interval could be definable in config. It is not necessary and it would be indeed bad thing to set a delay timer to fire an 'end of event' message. That would cause the issue that John is bringing up, no end message if the ongoing event is moved or deleted. 
The node should simply report on every polling is there is an event or not. If the ongoing event is moved or deleted, on the next polling the node will indicate 'no event' and that is the end message that John thinks could go missing.
The functionality to parse the event summary with a regex is not necessary; as the node reports that summary in msg, a user can do that himself if he needs that.

So, maybe the current node is too complex? Take a look at homebridge-calendar. I use that one and it does exactly what I need reliably. The only piece missing is that is does not report event details but only a simple true or false; that is due toi the different objective of himebridge as a portal to expose HomeKit accessories. As homebridge-calendar is node.js-based as well it should be simple to adapt for node-red.

My needs are simple and - for example - I have no overlapping events and such.

regards, andré hartman, belgium

**Comment by naimo84** [comment] 2019-11-01 08:26
Hi André, John,

> In my view the node regularly polls the calendar, polling interval could be definable in config.

A cron could be the same as a polling interval? polling every 5 minutes => cron */5 * * * *

But now I got your idea behind this 😄 

The node should not generate a output when the event triggers start/end, 
but every, for example, 5 minutes if there is a event ongoing or not?

I would create a third node for this. I'm sure, people already use the current functionality. 
What's a good name for this?
What's the output look like, if there are overlapping events?

And please be patient with me, spare time is rare currently.

regards, benjamin

**Comment by ahartman** [comment] 2019-11-01 08:44
Benjamin, John,

A cron could certainly control the polling interval but is a very technical thing. I, for one, would not know how to define one. That is why I said, cron should be internal to the node with a polling interval parameter in the config. I know cron offers much more power to a user than that but if do not know how to user it, it is of no value. It has value keeping node functionality simple, focus and not like a "Swiss army knife".

For now, your two nodes are little different; Events telles me about what is the first object in the Upcoming array. I would rebuild Event into a truly event-driven sensor event yes/no. Then they have really different value to a user. Also, you then need not find a new name for a third node! "Event" seems to be an apt name. If you prefer to build a third node, I propose to rename current "Event" into "Next Event"?

I can still remember when I have your kids getting you up at all hours during the night; not they are taller than me and at university.

regards, André Hartman, belgium

**Comment by naimo84** [comment] 2019-11-05 18:57
Hi,

I tried to implement it with the commit c93b273f68ec5492d332ff6d946efe60ec95f2f3.
I made a third node, because of backward compatibility. It's called "sensor node".

But: I'm not sure, whats the best name for the message property.
Currently it's a boolean called on. So, if  the current time is within eventStart and eventEnd, "on: true" is returned. Otherwise, "on: false".

If there is more than one event at the same time, multiple messages with "on: true" are returned.

What do you think about the property "on"?

**Comment by jseg** [comment] 2019-11-05 19:52
Maybe but the event summary in msg.topic?

**Comment by ahartman** [comment] 2019-11-06 06:58
For me, a property "On" with true of false is perfect. Many other sensor nodes do that and the output can be used directly to control other nodes. Please let me know when published and I will test it. Keep up the good work.
Regards, André Hartman

**Comment by naimo84** [comment] 2019-11-06 18:22
Can you give me an example of one of those nodes? A quick google search did not return a node with an “on” property 😉 thanks for your support 
Regards, Benjamin

**Comment by naimo84** [comment] 2019-11-07 14:09
Please have a look at version 0.6.0 :wink:

**Comment by ahartman** [comment] 2019-11-07 14:45
I will do so and let you know.
Also you find attached two examples of sensor output, modeled in Node-Red
The first is a Homebridge dummy switch; as you can see it gives "On": true and "On": false.
The second is my current Homebridge Event component; this is modeled as a contact sensor, a Homekit limitation. It gives "ContactSensor": 1 and "ContactSensor": 0, which I transform into "On": true and "On,": false.  

<img width="1191" alt="Schermafbeelding 2019-11-07 om 15 41 31" src="https://user-images.githubusercontent.com/688316/68398835-a9375a80-0175-11ea-8c48-0f5804d3f977.png">

**Comment by naimo84** [comment] 2019-11-08 05:51
Thanks for the example 😉 

A big difference is that, my on is lowercase and directly attached to msg.
The Homebridge Event is UpperCamelCase On and attached to msg.payload.

Should I change this? I don't know other nodes, wich are using msg.payload.On 😄

**Comment by ahartman** [comment] 2019-11-08 09:15
Benjamin,
I think it is not really important how you set it, since the user can always change it with a change node.

I tested your version 0.6.0 and I used the "old" public URL access as well as the secure method, that you recently coded.

The new sensor node give "undefined" in both cases.

For the "upcoming" node I defined 1 preview day, which means today.
With the shared URL I get back 2 events for today, which is correct.
With the secure URL, I get only one event!

Please see attached screen dumps
Regards, André Hartman

<img width="971" alt="public shared url" src="https://user-images.githubusercontent.com/688316/68464213-8443f580-0210-11ea-82b2-4ef5582eb79f.png">
<img width="971" alt="secure url" src="https://user-images.githubusercontent.com/688316/68464214-8443f580-0210-11ea-9f7e-241d3a673bd4.png">

**Comment by naimo84** [comment] 2019-11-09 08:13
The undefined comes from this 😉 Your debug node doesn't show the complete message, only msg.payload.

> A big difference is ... directly attached to **msg.**
> The Homebridge Event is ... attached to **msg.payload**.

I've to review my code, why there is only one event. Will report back

**Comment by ahartman** [comment] 2019-11-09 15:27
Benjamin,

I checked the complete message and the content is there.
However, I think it is is more convenient and more conventional to put the result in playload since ultimately that is what is, the payload.



Met vriendelijke groeten, Kind regards, Meilleures salutations,
André Hartman

**Comment by ahartman** [comment] 2019-11-11 07:37
Benjamin,

First the good news. I must have done something wrong at the first testing; 'upcoming events' and the 'sensor' nodes now work perfectly with a shared setup as well as with the secure setup.

I found one thing which I consider a bug: 'no event' is in 'msg.on: false' and an 'active event' is in 'msg.payload.on: true'. Properties should always be in the same place; I would move the 'no event' message to 'msg.payload.on: false'.

What I find now if that the sensor node emits a message at every check. However, an event node should only notify changes and not status. What you could do is two outputs, one emitting changes only and one emitting status at every check. I saw this in the node-red big-timer node and it would give users maximum flexibility.

I think the config options can cause confusion:
iCal: this option reads from iCloud, like the iCloud option does with a public, non-secure URL. I would call this one 'iCloud public'.
iCloud. I would call this one 'iCloud secure'.
Caldav. This one is confusing as well since iCloud is also caldav standard. Maybe call this 'caldav generic'?

Regards, André Hartman, Belgium

**Comment by naimo84** [comment] 2019-11-11 09:42
André,

I thought, it's the right behavior :wink:

> The node should simply report on every polling is there is an event or not.

I will change this to 2 outputs.

---
The msg.payload.on: false will be fixed with the next version, I already changed it.

---



> I think the config options can cause confusion:
> iCal: this option reads from iCloud, like the iCloud option does with a public, non-secure URL. I would call this one 'iCloud public'.
> iCloud. I would call this one 'iCloud secure'.

Because the node can also be used with other iCal/CalDav URLs, I'd like to keep the current naming.

iCloud --> iCloud secure might be worth changing. And adding a help message, how to get a secure URL :wink:

> Caldav. This one is confusing as well since iCloud is also caldav standard. Maybe call this 'caldav generic'?

I'm using this package https://www.npmjs.com/package/dav for getting CalDav events. But the iCloud CalDav does not work... i have no idea why... So I implemented a similiar code as the homebridge modules does.

That's why there is a third type for "iCloud secure"

**Comment by naimo84** [comment] 2019-11-12 21:09
Version 0.8.0 should now contain 
- two outputs,
- a regex filter with always, match and no match
- always msg.payload.on

**Comment by davidscottparker** [comment] 2019-11-16 10:10
Hi Benjamin, I have been checking out your ical "sensor" node with google calendar as a replacement for a whole load of code I had to write to achieve the same thing, ie obtain the status of a CURRENT event, and with mostly good results ... but ... I have noticed that the sensor node does not always get the latest calendar setting if the event has changed, almost like it is referring to a cached event rather than the actual event. Below is the payload for an event that has been shortened to end at 08.00am.

{"summary":"Central Heating","topic":"Central Heating","id":"4qms97g14kek7rpl6r25of3h0r@google.com","location":"","eventStart":"2019-11-16T07:00:00.000Z","eventEnd":"2019-11-16T11:00:00.000Z","description":"","on":true}

Any assistance would be greatly appreciated, thanks, Dave

**Comment by ahartman** [comment] 2019-11-16 15:35
David,
I have been working intensively with the ical nodes recently, albeit with iCloud calendars.

Two quick suggestions to help you find the root cause:
= the Sensor node has a refresh interval; make that really short and see what happens
= the 'Upcoming' node gives you a list of future events; see if the calendar event gets correctly updated in that node.

Regards, ahartman, belgium

**Comment by davidscottparker** [comment] 2019-11-16 17:30
Hi André

Thanks for the feedback. I have a 10 second refresh for testing and was going to drop to 1 minute for production and started to look at the upcoming node, but didn't complete as I needed to research cron syntax as I have not used this before.

I'll try the whole thing also with iCloud calendars just to see if there is a difference.

I guessing that all is good with your setup?

Kind regards, Dave

**Comment by ahartman** [comment] 2019-11-16 18:03
Dave,
I have not yet found a single updating issue with iCloud calendars. They refresh instantly on the first sensor node polling.
Why do you need cron-stuff; I read about it but did not yet need to 
use this.

Regards, André Hartman

**Comment by naimo84** [comment] 2019-11-18 07:22
Hi Dave, hi André,

I'll have a look at this. From my side, there is no caching mechanism :wink: I'm always reading the current ical/icloud/... events.

I'll report back, if I find the bug :bug:

regards, benjamin

**Comment by davidscottparker** [comment] 2019-11-18 08:16
Thank you

**Comment by davidscottparker** [comment] 2019-11-18 21:09
Thanks again for looking into this -I seem to have a stable system right now accessing about 15 different calendars, so it may well have been finger trouble on my part.

**Comment by naimo84** [comment] 2019-11-19 05:59
Nice to hear/read, it's working :wink:

I'm closing this issue. Feel free to open a new one 👍

**Closed by naimo84** 2019-11-19 05:59 UTC
